//
//  StyleKitPromo.h
//  CMV
//
//  Created by Massimo moro on 01/02/17.
//  Copyright (c) 2017 CAsinò di Venezia Gioco Spa. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitPromo : NSObject

// Drawing Methods
+ (void)drawCanvas1WithFrame: (CGRect)frame;

@end
